spring:
  profiles:
    active: dev
app:
  upload:
    dir: C:/imagenes/uploads


#spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:prod} # Por defecto prod
#app:
#  upload:
#    dir: ${UPLOAD_DIR:/app/uploads} # Volumen Docker